version: 2.1

dockername: &dockername
  docker:
    - image: circleci/node:13.8.0

jobs:

  build:
    <<: *dockername
    steps:
      - checkout
      - run:
          command: npm i
      - save_cache:
          key: "npm packages"
          paths: 
            - /src/node_modules
      - run:
          command: npm run lint

  test:
    <<: *dockername
    steps:
      - checkout
      - restore_cache:
          key: "npm packages"
      - run: npm i
      - run: npm run test

  analyze:
    <<: *dockername
    steps:
      - checkout
      - run: npm audit

workflows:
  pipeline_for_test:
    jobs:
      - build
      - test:
          requires: [build]
      - analyze:
          requires: [test]